### ISSUE TITLE
Decryption is incorrectly printing a mix of decimal ASCII values and text

### ISSUE THREAD

**Issue by joshuarbholden** [motarekk/motarekk.github.io#1]
Pretty sure this is a bug; decryption is outputting a mix of decimal ASCII values and text:

![image](https://github.com/motarekk/motarekk.github.io/assets/5004948/3a6c496d-8c89-4859-be0c-d5b4a58c82c7)
![image](https://github.com/motarekk/motarekk.github.io/assets/5004948/4d91e360-8e86-4569-a22f-b96f22a74ff0)

[Testing done in Firefox 116.0.3 (64-bit) on Microsoft Windows 10 Enterprise, Version 10.0.19045 Build 19045]

**Comment by motarekk** [comment]
Indeed. I've fixed it now. You can check it in commit [b3ccb7d]:(https://github.com/motarekk/motarekk.github.io/commit/b3ccb7d6fd454ea75c920ff34ee37cbac96c4f9a)

You can also retest it and confirm it's not producing the same issue.
Thanks.

**Comment by motarekk** [comment]
Update: I've added a hall of fame as a thanks for all who reported bugs and contributed in enhancing this tool.

**Comment by joshuarbholden** [comment]
Cool, thanks!  I'm expecting this website to be very useful next time I teach cryptography.
