### ISSUE TITLE
There is an inconsistency in the calculation result, and I am not sure which one is correct.

### ISSUE THREAD

**Issue by topmin** [motarekk/motarekk.github.io#2]
![无标题](https://github.com/motarekk/motarekk.github.io/assets/57675026/33431d6d-da75-4054-a8cb-417165645b24)

**Comment by motarekk** [comment]
@topmin Thanks for reaching out.
"d192" is the correct result, and it matches the result from pyascon (the python implementation by Maria Eichlseder [https://github.com/meichlseder/pyascon]).
<img width="327" alt="pyascon_demo" src="https://github.com/motarekk/motarekk.github.io/assets/104282801/3b2fefb8-1a2a-43bb-bca8-c0f7c1c178cd">

**Comment by topmin** [comment]
d192 is correct, I have corrected my code.
Thank you!

plaintext: 3000
sKey: 31323334353637383930616263646566
nonce: 31323334353637383930616263646566
ciphertext: d192
tag: fb95619571e3aa1e3daa4b195f669dc5
hash: 86b67c29eb33d54218e9b4acc6ebf9cd193e52f2bf4e7b8cd12c1b5180c83bdb

plaintext: 3000310032003300340035003600370038003900
sKey: 31323334353637383930616263646566
nonce: 31323334353637383930616263646566
ciphertext: d1929b1fad6ff4a5a63cb6e2fbf93032e4560ff2
tag: 7607f296492f125a9ec2b3240f0bf582
hash: 68872fc082e40301a090b0510feed8709c4aa22bc0cbb84ac2133a95f52fc9e7

![3000](https://github.com/motarekk/motarekk.github.io/assets/57675026/8b94e5e0-aa03-450c-a78b-230042c95e69)
![123456789](https://github.com/motarekk/motarekk.github.io/assets/57675026/0e206df1-e54d-447b-915f-ba571f77f40a)
